import TickerInfo from "@/components/TickerInfo";
import TradesTable from "@/components/TradesTable";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: { symbol: string };
};

export default function RootLayout({
  children,
  params: { symbol },
  params,
}: Props) {
  symbol = `t${decodeURIComponent(symbol).replace(":", "").toUpperCase()}`;

  return (
    <main className="flex flex-col lg:flex-row gap-6 items-start">
      <section className="space-y-6">
        <TickerInfo symbol={symbol} params={params} />
        <TradesTable symbol={symbol} />
      </section>
      {children}
    </main>
  );
}
