import TickersHeader from "@/components/TickersHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="max-w-7xl mx-auto">
      <TickersHeader />
      {children}
    </main>
  );
}
